field = [7681, 10753, 11777, 12289, 13313, 15361]

def intt(a):
    print("#[target_feature(enable = \"avx2\")]")
    print("pub unsafe fn intt_"+str(a)+"(s0: [__m256i;16]) -> [__m256i;16]{")
    print("    let s1 = intt5678_"+str(a)+"(s0);")
    print("    let s2 = transpose(s1);")
    print("    let s3 = intt1234_"+str(a)+"(s2);")
    print("    s3\n}\n")


def intt_l1(a):
    print("#[target_feature(enable = \"avx2\")]")
    print("pub unsafe fn intt1234_"+str(a)+"(a: [__m256i;16]) -> [__m256i;16]{")
    print("    let mut a0: [__m256i;16] = [_mm256_setzero_si256(); 16];")
    print("    let mut a1: [__m256i;16] = [_mm256_setzero_si256(); 16];")
    print("    // let l1 ~ l4")
    print("    // inverse Layer 4")
    print("    for i in 0..8{")
    print("        [a0[2*i], a0[2*i+1]] = barrett_ibutterfly_"+str(a)+"(a[2*i], a[2*i+1], l4[2*i], l4[2*i+1]);")
    print("    }")
    print("    // inverse Layer 3")
    print("    for i in 0..4{")
    print("        for j in 0..2{")
    print("            [a1[i*4+j], a1[i*4+j+2]] = barrett_ibutterfly_"+str(a)+"(a0[i*4+j], a0[i*4+j+2], l3[2*i], l3[2*i+1]);")
    print("        }")
    print("    }")
    print("    // inverse Layer 2")
    print("    for i in 0..4{")
    print("        [a0[i], a0[i+4]] = barrett_ibutterfly_"+str(a)+"(a1[i], a1[i+4], l2[0], l2[1]);")
    print("        [a0[i+8], a0[i+12]] = barrett_ibutterfly_"+str(a)+"(a1[i+8], a1[i+12], l2[2], l2[3]);")
    print("    }")
    print("    // inverse Layer 1")
    print("    for i in 0..8{")
    print("        [a1[i], a1[i+8]] = barrett_ibutterfly_"+str(a)+"(a0[i], a0[i+8], l1[0], l1[1]);")
    print("    }")
    print("    a1")
    print("}\n")

def intt_l2(a):
    print("#[target_feature(enable = \"avx2\")]")
    print("pub unsafe fn intt5678_"+str(a)+"(a: [__m256i;16]) -> [__m256i;16]{")
    print("    let mut a0: [__m256i;16] = [_mm256_setzero_si256(); 16];")
    print("    let mut a1: [__m256i;16] = [_mm256_setzero_si256(); 16];")
    print("    // let l5 ~ l8")
    print("    // inverse Layer 8")
    print("    for i in 0..8{")
    print("        [a0[2*i], a0[2*i+1]] = barrett_ibutterfly_"+str(a)+"(a[2*i], a[2*i+1], l8[2*i], l8[2*i+1]);")
    print("    }")
    print("    // inverse Layer 7")
    print("    for i in 0..4{")
    print("        for j in 0..2{")
    print("            [a1[i*4+j], a1[i*4+j+2]] = barrett_ibutterfly_"+str(a)+"(a0[i*4+j], a0[i*4+j+2], l7[2*i], l7[2*i+1]);")
    print("        }")
    print("    }")
    print("    // inverse Layer 6")
    print("    for i in 0..4{")
    print("        [a0[i], a0[i+4]] = barrett_ibutterfly_"+str(a)+"(a1[i], a1[i+4], l6[0], l6[1]);")
    print("        [a0[i+8], a0[i+12]] = barrett_ibutterfly_"+str(a)+"(a1[i+8], a1[i+12], l6[2], l6[3]);")
    print("    }")
    print("    // inverse Layer 5")
    print("    for i in 0..8{")
    print("        [a1[i], a1[i+8]] = barrett_ibutterfly_"+str(a)+"(a0[i], a0[i+8], l5[0], l5[1]);")
    print("    }")
    print("    a1")
    print("}\n")

for f in field:
    intt(f)
    intt_l1(f)
    intt_l2(f)